"""Interactive wizard: creates .mcp-memory-ydb.env and prints connection commands."""
from __future__ import annotations

import json
import sys
from pathlib import Path


def run_setup() -> None:
    print("=== mcp-memory-ydb setup ===")
    print("Creates .mcp-memory-ydb.env and shows the commands to connect.\n")

    def ask(prompt: str, default: str = "") -> str:
        suffix = f" [{default}]" if default else ""
        val = input(f"{prompt}{suffix}: ").strip()
        return val or default

    # ── LLM ──
    print("── LLM (for mem0 fact extraction) ──")
    print("  Provider          Base URL                                  Model")
    print("  Yandex Cloud      https://llm.api.cloud.yandex.net/v1       gpt://folder_id/yandexgpt-5.1/latest")
    print("  OpenAI            https://api.openai.com/v1                 gpt-4o-mini")
    print("  Ollama            http://localhost:11434/v1                  llama3")
    llm_base_url = ask("  Base URL")
    llm_model = ask("  Model")
    llm_api_key = ask("  API Key")

    # ── Embeddings ──
    print("\n── Embeddings (for vector search) ──")
    print("  Provider          Base URL                                  Model")
    print("  Yandex Cloud      https://llm.api.cloud.yandex.net/v1       emb://folder_id/text-search-query/latest")
    print("  OpenAI            https://api.openai.com/v1                 text-embedding-3-small")
    print("  Ollama            http://localhost:11434/v1                  nomic-embed-text")
    emb_same = ask("  Same Base URL and API Key as the LLM? (y/n)", "y").lower()
    if emb_same == "y":
        emb_base_url = ""
        emb_api_key = ""
    else:
        emb_base_url = ask("  Base URL")
        emb_api_key = ask("  API Key")
    emb_model = ask("  Model")

    # ── Namespace ──
    print("\n── Memory ──")
    print("  Namespace partitions memory (e.g. one per project or agent).")
    print("  It is a filter label, not a security boundary — see the README.")
    memory_namespace = ask("  Memory namespace", "default")

    # ── Fact-extraction instructions (language) ──
    print("\n  By default facts are stored in English (mem0's prompt is English).")
    print("  To keep the user's language, type an instruction IN that language,")
    print("  e.g. (RU): Сохраняй каждый факт на языке исходного сообщения, не переводи.")
    print("  (The model honors a same-language directive far more reliably.)")
    fact_instructions = ask("  Fact-extraction instruction (empty = mem0 default)", "")

    # ── YDB ──
    print("\n── YDB Serverless ──")
    ydb_endpoint = ask("  Endpoint", "grpcs://ydb.serverless.yandexcloud.net:2135")
    ydb_database = ask("  Database (/ru-central1/<folder>/<db>)")
    ydb_sa_key_file = ask("  SA key file path (service-account JSON key, role ydb.editor)", "")

    # ── Write .mcp-memory-ydb.env ──
    lines = [
        "# Generated by mcp-memory-ydb setup. Edit as needed.",
        "",
        f"LLM_BASE_URL={llm_base_url}",
        f"LLM_MODEL={llm_model}",
        f"LLM_API_KEY={llm_api_key}",
        "",
        f"EMBEDDINGS_MODEL={emb_model}",
        "",
        f"MEMORY_NAMESPACE={memory_namespace}",
    ]
    if fact_instructions:
        lines.append(f"MEMORY_FACT_INSTRUCTIONS={fact_instructions}")
    if emb_base_url:
        lines.append(f"EMBEDDINGS_BASE_URL={emb_base_url}")
    if emb_api_key:
        lines.append(f"EMBEDDINGS_API_KEY={emb_api_key}")
    lines += [
        "",
        f"YDB_ENDPOINT={ydb_endpoint}",
        f"YDB_DATABASE={ydb_database}",
    ]
    if ydb_sa_key_file:
        lines.append(f"YDB_SA_KEY_FILE={ydb_sa_key_file}  # service-account JSON key (role ydb.editor)")
    lines += [
        "",
        "MEMORY_THRESHOLD=0.15              # minimum cosine score for memory_search",
    ]

    default_path = Path.home() / ".mcp-memory-ydb.env"
    env_path = Path(ask("  Save to", str(default_path)))
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n✓ Written to {env_path.absolute()}")

    # ── Instructions ──
    bin_path = str(Path(sys.executable).parent / "mcp-memory-ydb").replace("\\", "/")
    print("\n" + "─" * 60)
    print("Connect to your agent:")
    print("\n● Claude Code (global install):")
    print("   claude mcp add --scope user memory-ydb -- mcp-memory-ydb")
    print("\n● Claude Code (current environment):")
    print(f"   claude mcp add --scope user memory-ydb -- {bin_path}")
    print("\n● Cursor / Windsurf / VS Code — add to the MCP config:")
    cursor_cfg = {"mcpServers": {"memory-ydb": {"command": bin_path, "args": []}}}
    print(json.dumps(cursor_cfg, indent=2, ensure_ascii=False))
    print("\nThe server ships MCP instructions, so memory usually works automatically.")
    print("If your client ignores them, add this to the agent's system prompt:")
    print("   Before answering, call memory_search for relevant context.")
    print("   After answering, call memory_save if you learned something important.")
    print("   When a new fact supersedes an old one, memory_delete / memory_update its id.")
    print("─" * 60)
